### ISSUE TITLE
Making background color respect firefox color theme

### ISSUE THREAD

**Issue by 0xda157** [krishna-godoi/firefox#1]
In your readme you mention hardcoded values for some colors. I already solved this (seems I need better documentation :/). Starting on line 27 of `userChrome.css` there is this block of code:
```css
@media (prefers-color-scheme: light) {
    --user-bg: rgb(239, 239, 242) !important;
    @media (-moz-bool-pref: "uc.tweak.translucency") {
        --user-bg: color-mix(in srgb, rgb(239, 239, 242), transparent 20%) !important;
    }
}

@media (prefers-color-scheme: dark) {
    --user-bg: rgb(27, 26, 32) !important;
    @media (-moz-bool-pref: "uc.tweak.translucency") {
        --user-bg: color-mix(in srgb, rgb(27, 26, 32), transparent 20%) !important;
    }
}

&[lwtheme="true"] {
    --user-bg: var(--lwt-accent-color) !important;
    @media (-moz-bool-pref: "uc.tweak.translucency") {
        --user-bg: color-mix(in srgb, var(--lwt-accent-color), transparent 20%) !important;
    }
}
```
It will automatically uses the firefox color's color for the background, just change the transparency* and light/dark mode (for when firefox color isn't active) values to fit your theme. You will also need to change line 21 in `main.css` to `background-color: var(--user-bg) !important;`. Thanks for giving me credit, but keep in mind if you people to be able to remix your code, as you did with mine, you need to make it all licensed under an open source/free software license (such as [MPL v2](https://www.mozilla.org/en-US/MPL/2.0/)) by including a `LICENSE` file.

*note that that translucency values are inverted, i.e. 20% = 80% translucency
